### PR TITLE
languages.json: Add missing Greek (el) characters

### PR DESCRIPTION
**Pull request by typerslow**
The following characters are added: Ϊ, Ϋ, ΐ, ΰ, ϊ, ϋ.

### CODE REVIEW

**Comment by orsinium** [comment]
Great! Thank you

**Comment by orsinium** [comment]
Released in 2.0.2

**Comment by orsinium** [comment]
That's your second PR overall, right? Welcome!

**Comment by typerslow** [comment]
Yes it is, thanks!

**Pull request merged**
